package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting definition. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLDefinition extends AbstractDefinition {

    /**
     * constructor.
     */
    public CMLDefinition() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLDefinition(CMLDefinition old) {
        super((AbstractDefinition) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLDefinition(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLDefinition
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLDefinition();

    }
}
