// /*======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ======*/
package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

/** fragment normally contains molecules.
*
* 
* \n \nfragment is a container for a molecule, potentially to be joined
*  to other fragments. In addition there may be fragmentLists which
*   represent branches from the molecule. There may also be a join
*    child which is normally only found if there is a @countExpression.
* 
* user-modifiable class autogenerated from schema if no class exists
* use as a shell which can be edited
* the autogeneration software will not overwrite an existing class file

*/
public class CMLFragment extends org.xmlcml.cml.element.AbstractFragment {

    /** must give simple documentation.
    *

    */

    public CMLFragment() {
    }
    /** must give simple documentation.
    *
    * @param old CMLFragment to copy

    */

    public CMLFragment(CMLFragment old) {
        super((org.xmlcml.cml.element.AbstractFragment) old);
    }

    /** copy node .
    *
    * @return Node
    */
    public Node copy() {
        return new CMLFragment(this);
    }
    /** create new instance in context of parent, overridable by subclasses.
    *
    * @param parent parent of element to be constructed (ignored by default)
    * @return CMLFragment
    */
    public static CMLFragment makeElementInContext(Element parent) {
        return new CMLFragment();
    }
    
}
