// /*======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ======*/
package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

/** Iterates through a list or list of values.
*
* 
* Experimental. 
* 
* user-modifiable class autogenerated from schema if no class exists
* use as a shell which can be edited
* the autogeneration software will not overwrite an existing class file

*/
public class CMLFor extends org.xmlcml.cml.element.AbstractFor {

    /** must give simple documentation.
    *

    */

    public CMLFor() {
    }
    /** must give simple documentation.
    *
    * @param old CMLFor to copy

    */

    public CMLFor(CMLFor old) {
        super((org.xmlcml.cml.element.AbstractFor) old);
    }

    /** copy node .
    *
    * @return Node
    */
    public Node copy() {
        return new CMLFor(this);
    }
    /** create new instance in context of parent, overridable by subclasses.
    *
    * @param parent parent of element to be constructed (ignored by default)
    * @return CMLFor
    */
    public static CMLFor makeElementInContext(Element parent) {
        return new CMLFor();
    }
}
